### PR TITLE
Colormaps

### PR DESCRIPTION
**Pull request by jatkinson1000**
This adds presentation and notebook materials on colormaps.

### CODE REVIEW

**Comment by j-emberton** [comment]
do we need to keep the Quarto extension files in the repo, or should we assume they are regenerated when the slides are rendered locally?

**Comment by jatkinson1000** [comment]
@j-emberton 
General advice from quarto is to keep these as otherwise end users need to reinstall.
I do often wonder if they could be submoduled somehow though.

**Review by j-emberton — APPROVED** [review]
lgtm

**Comment by jatkinson1000** [comment]
@j-emberton This is still very much work in progress, sorry!
I'mm mark as draft for now and then re-request a review and ping you once I feel it is ready :)

**Pull request merged**
